apiVersion: v1
kind: Service
metadata:
  name: service-drivers
spec:
  selector:
    app: service-drivers
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 33000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-drivers
spec:
  selector:
    matchLabels:
      app: service-drivers
  replicas: 1
  template:
    metadata:
      labels:
        app: service-drivers
    spec:
      containers:
        - name: server
          image: bozhko/drivers
          ports:
            - name: http
              containerPort: 8083

---